# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_subscriber_id', models.PositiveIntegerField()),
                ('email_address', models.CharField(max_length=200)),
                ('subscribed_at', models.DateTimeField(verbose_name='Subscribed At')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriberLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
            ],
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.NewsletterSubscriberLocation'),
        ),
    ]
