# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletters_subscriber_id', models.PositiveIntegerField()),
                ('email_address', models.CharField(max_length=200)),
                ('subscribed_at', models.DateTimeField(verbose_name='Subscribed At')),
            ],
        ),
        migrations.RenameModel(
            old_name='NewsletterSubscriberLocation',
            new_name='SubscriberLocation',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='location_id',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='newsletters_subscriber_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.SubscriberLocation'),
        ),
    ]
