# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20170220_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='newsletters_subscriber_id',
        ),
    ]
