# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_auto_20170222_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='newsletters_subscriber_location_id',
        ),
        migrations.DeleteModel(
            name='SubscriberLocation',
        ),
    ]
