# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_auto_20170222_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=200)),
                ('state_abv', models.TextField(max_length=15)),
                ('country', models.TextField(default='US', max_length=2)),
                ('population', models.PositiveIntegerField(null=True, verbose_name='Last Known Population')),
                ('population_estimate', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Estimated Population')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'newsletter_subscriber_locations',
            },
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_subscribed',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterModelTable(
            name='subscriber',
            table='newsletter_subscribers',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletters.SubscriberLocation'),
        ),
    ]
