# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0007_auto_20170222_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_at',
            field=models.DateTimeField(null=True, verbose_name='Unsubscribed At'),
        ),
    ]
