# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_subscriber_unsubscribe_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='unsubscribe_at',
            new_name='unsubscribed_at',
        ),
    ]
