# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0009_auto_20170223_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed At'),
        ),
    ]
